src/config/routes.rb
Rails.application.routes.draw do
  
  resources :conversations do
    resources :messages
  end
  devise_for :users
  root 'page#home'
  # root 'items#index'
  # resource :items

  get "/items", to: "items#index", as: "items"
  post "/items", to: "items#create"
  get "/items/new", to: "items#new", as: "new_items"
  get "/items/:id", to: "items#show", as: "item"
  put "/items/:id", to: "items#update"
  patch "/items/:id", to: "items#update"
  delete "/items/:id", to: "items#destroy"
  get "/items/:id/edit", to: "items#edit", as: "edit_items"
  post '/comment', to: 'comment#create', as: 'create_comment'
  post '/order_items', to: 'order_items#create', as: 'create_order_items'
  put "/order_items/:id", to: "order_items#update"
  patch "/order_items/:id", to: "order_items#update"
  get "/cards/", to: "cards#show", as: "cards"

  # get "/conversations", to: "conversations#index", as: "conversations"
  # post "/conversations", to: "conversations#create"
  # get "/messages", to: "messages#index", as: "conversation_messages"
  # post '/messages', to: 'messages#create', as: 'create_messages'
end

src/app/models/item.rb
class Item < ApplicationRecord
	belongs_to :user
	belongs_to :category
	has_many :order_items, dependent: :destroy
	has_many :comments, dependent: :destroy
	validates :title, presence: true
	has_one_attached :image
	
end

src/app/controllers/items_controller.rb
class ItemsController < ApplicationController
before_action :authenticate_user!
 before_action :find_item, only: [:show, :edit, :update, :destroy]

  def index
  	@items = Item.all
    @order_items = current_order.order_items.new
    if params[:category].blank?
    @items = Item.all
  else
    @category_id = Category.find_by(name: params[:category]).id
      @items = Item.where(:category_id => @category_id)
   end

  end

  def new
  	 @item =  current_user.items.create
      #@oder_items = OrderItem.current_order.order_item.new
     
     @categories = Category.all.map{ |c| [c.name, c.id] } 
  end

  def create
   # @oder_items = OrdertIem.current_order.order_item.create(item_params)
  	@item = current_user.items.create(item_params)
     #@item.category.id = params[:category_id]
  	if @item.save
  		redirect_to items_path
    else
      @categories = Category.all.map{ |c| [c.name, c.id] } 
  		render "new"
  	end

  end

  def show

   

   @items = Item.where(:category_id => @category_id)
   
   @comments = Comment.all
   
   @order_item = current_order.order_items.new
  end



  def update
     
    if @item.update(item_params)
      redirect_to items_path
    else
      render "edit"
    end
end





   def edit
    @categories = Category.all.map{ |c| [c.name, c.id] }
     
   end
   
  def destroy
  Item.find(params[:id]).destroy
   redirect_to items_path
      
    
  end


   private

   def find_item
    @item = Item.find(params[:id])
   end


   def item_params
   	params.require(:item).permit(:title, :description, :size, :color, :price, :category_id, :quantity, :order_item_id, :image)
   	
   end

   
end

src/app/helpers/items_helper.rb
module ItemsHelper
end

src/app/views/items/_form.html.erb
<% if item.errors.any? %>
    <div class="errors">
        <% item.errors.full_messages.each do |error| %>
            <p><%= error %></p>
        <% end %>
    </div>
<% end %>
<%= form_with model: item, local: true do |form| %>
<div>
  
  <%= form.select :category_id, @categories %>
</div>
  <div>
  	<%= form.label :title %>
  	<%= form.text_field :title, value: item.title %>
  </div>
   <div>
  	<%= form.label :description %>
  	<%= form.text_field :description, value: item.description%>
  </div>
   <div>
  	<%= form.label :size %>
  	<%= form.text_field :size, value: item.size %>
  </div>
   <div>
  	<%= form.label :color %>
  	<%= form.text_field :color, value: item.color %>
  	 <div>
  	<%= form.label :price %>
  	<%= form.number_field :price, value: item.price %>
  </div>
  <div>
    <%= form.label :image %>
    <%= form.file_field :image %>
    
  </div>
  <div>
 	<%= form.submit value: "Create" %>
  </div>

<% end %>

src/app/views/items/edit.html.erb
<h1>Edit</h1>


<%= render 'form', item: @item %>

src/app/views/items/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
   
    <title>Greatdeal | index </title>
  </head>
  <body>

<section>

  <h2 style="text-align:center">Welcome to Greatdeal</h2>

   <div class="container">
  <div class="mySlides">
    <div class="numbertext">1 / 6</div>
    <img src="/assets/sliceshow.jpg" style="width:100%">
   
  </div>

  <div class="mySlides">
    <div class="numbertext">2 / 6</div>
    <img src="/assets/sliceshow1.jpeg" style="width:100%">
  </div>

  <div class="mySlides">
    <div class="numbertext">3 / 6</div>
    <img src="/assets/sliceshow2.jpg" style="width:100%">
  </div>
    
  <div class="mySlides">
    <div class="numbertext">4 / 6</div>
    <img src="/assets/sliceshow3.jpg" style="width:100%">
  </div>

  <div class="mySlides">
    <div class="numbertext">5 / 6</div>
    <img src="/assets/sliceshow4.jpg" style="width:100%">
  </div>
    
  <div class="mySlides">
    <div class="numbertext">6 / 6</div>
    <img src="/assets/sliceshow5.jpg" style="width:100%">
  </div>
    
  <a class="prev" onclick="plusSlides(-1)">❮</a>
  <a class="next" onclick="plusSlides(1)">❯</a>

  <div class="caption-container">
    <p id="caption"></p>
  </div>

  <div class="row">
    <div class="column">
      <img class="demo cursor" src="/assets/sliceshow.jpg" style="width:100%"> style="width:100%" >
    </div>
    <div class="column">
      <img class="demo cursor" src="/assets/sliceshow1.jpeg" style="width:100%" onclick="currentSlide(2)" alt="Cinque Terre">
    </div>
    <div class="column">
      <img class="demo cursor"  src="/assets/sliceshow2.jpg" style="width:100%" onclick="currentSlide(3)" alt="Mountains and fjords">
    </div>
    <div class="column">
      <img class="demo cursor"  src="/assets/sliceshow3.jpg" onclick="currentSlide(4)" alt="Northern Lights">
    </div>
    <div class="column">
      <img class="demo cursor"  src="/assets/sliceshow4.jpg" onclick="currentSlide(5)" alt="Nature and sunrise">
    </div>    
    <div class="column">
      <img class="demo cursor"  src="/assets/sliceshow5.jpg" onclick="currentSlide(6)" alt="Snowy Mountains">
    </div>
  </div>
</div>

</section>

<section>

<div>

<ul>
<li><%=link_to "View All", items_path%></li>
   <% Category.all.each do |category| %>
 
   <li class="<%'active' if params[:category ] == category.name%>">
   <%= link_to category.name, items_path(category: category.name)%>
   </li>
  
 <% end %> 
 
  </ul>
  <% params[:category]%>
  <% if @items.count == 0%>
   <p>There are no items currently in this category</p>
 <% else %> 
 </div>  

<div>
 <div class="items">
 
 <% @items.each do |item|%> 
    <div class="item">
           <div class="info">
          <div class="info-bar">
          <%= link_to item_path(item.id)do %>
          <%= image_tag item.image if item.image.attached?  %>  
          <% end %>
            <a><%= link_to item.category.name, item_path(item.id),  class: "link" %></a>
            <p><%= link_to item.title, item_path(item.id),  class: "link" %> </p>
            <p><%= link_to number_to_currency(item.price), item_path(item.id), class: "link"%></p>
            
         </div>
        </div>
    </div>
<% end %>
<% end %>

</section>



 


  
<h1> <%= link_to "Add item", new_items_path %></h1>





  </body>

 
  </html>

src/app/views/items/new.html.erb
 <h1> new </h1>

 <%= render 'form', item: @item %>

src/app/views/items/show.html.erb
  
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  
<section>
<div class="container">
  <div class="row">
   <div class="col-sm-6">
      <%= image_tag(@item.image) if @item.image.attached? %>
    </div>
    <div class="col">
      <br>
      <br>
      <br>
      
      <h3 class="text-muted"><%=@item.category.name%></h3>
      <h4 class="text-muted"><%=@item.color%></h4>
       <h2 class="price"> <%=@item.price%></h2>
        <h2> <%=@item.title%></h2>
        <p> <%=@item.description%></p>
       
        <br>

        <br>
         <h4 class="text-muted">Size: <%=@item.size%></h4>
       <%= form_with model: @order_item, url: create_order_items_path, local: true, method: "post" do |form| %>
      <%= form.hidden_field :item_id, :value => @item.id%>
      <%= form.number_field :quantity, :value => 1, :min =>  1%>
      <%= form.hidden_field :user_id, :value => current_user.id%>
     
     
     <button type="button" class="btn btn-secondary"><i class="fa fa-shopping-cart" style="font-size:20px;color:white">  <%= form.submit"Add to cart"%></i></button>
     
     <br>
     <br>
     
     <button type="button" class="btn btn-info btn-lg "><i class="fa fa-shopping-cart" style="font-size:20px;color:white"><%= link_to " Your current cart", cards_path, class: "cart"%> </i></button>
      <% end %>
      <br>
      <br>
    <% if user_signed_in? && current_user.id != @item.user_id %>
      <button type="button" class="btn btn-info btn-lg "><%= link_to "Message #{@item.user.email}", conversations_path(sender_id: current_user.id, recipient_id: @item.user.id), method: 'post', class:"button is-link", class: "cart" %></button>
    <% elsif user_signed_in? && current_user.id == @item.user_id  %>
      <%= link_to "Conversations", conversations_path %>
    <% else %>

    <%= link_to "Sign up to message #{@item.user.email}", new_user_registration_path %>
    <% end %>
    </div>

  </div>
</div>
<br>
<br>



</section>


<section>
  <h2 class="display-4 text-center py-5 my-4">Description</h2>
  <nav class="nav justify-content-center nav-pills flex-column flex-md-row">
    <a class="nav-link active" href="#first" data-toggle="tab">first</a>
    <a class="nav-link" href="#second" data-toggle="tab">Second</a>
    <a class="nav-link" href="#third" data-toggle="tab" >third</a>
    <a class="nav-link" href="#fourth" data-toggle="tab" >fourth</a>
  </nav>
   <div class="tab-content py-5">
     <div class="tab-pane active"id="first">
       <h3>first</h3>
       <p>ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmodtempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam</p>
     </div>
   </div>

   <div class="tab-content py-5">
     <div class="tab-pane"id="second">
       <h3>second</h3>
       <p>ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmodtempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam</p>
     </div>
   </div>

   <div class="tab-content py-5">
     <div class="tab-pane"id="third">
       <h3>third</h3>
       <p>ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmodtempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam</p>
     </div>
   </div>

   <div class="tab-content py-5">
     <div class="tab-pane"id="fourth">
       <h3>fourth</h3>
       <p>ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmodtempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam</p>
     </div>
   </div>
</section>

<section>
   
 <h1>You may also like</h1>
   <% Item.where(category_id:@item.category.id).each do |item| %>
   
  <%if item.id != @item.id %>
   <div class="item">
       <div class="info">
     <div class="info-bar">
       <%= link_to item_path(item.id)do %>
            <%= image_tag item.image if item.image.attached?  %>  
            <% end %>
              <a><%= link_to item.category.name, item_path(item.id),  class: "a-primary" %></a>
              <p><%= link_to item.title, item_path(item.id),  class: "a-primary" %> </p>
              <p><%= link_to number_to_currency(item.price), item_path(item.id), class: "a-primary"%></p>
              
           </div>
          </div>
      </div>

<%end%>
 <% end %> 
</section>

<section>
<div class="container text-center">

  <%= form_with model: @comment, url: create_comment_path, local: true, method: "post" do |form| %>

    <h3><%= form.label :"Enter your comment here"%></h3>
    
    <%= form.text_field :text_field, class: "text-area" %>
    <br>
    <%= form.hidden_field :item_id, :value => @item.id %>

    <%= submit_tag "submit", class: "sub" %>
  </div>
</div>

<% end %>
  
  
 <div class="container text-center">
 <h3> Comments </h3>
<% @comments.each do |comment| %>
 <div class="row">
    <div class="col">

    <% if comment.item_id == @item.id %>
     
        <h4 class="mx-3"> comment From<%= User.find(comment.user_id).email %> </h4>
    
       <h6  class="mx-3"> <%= comment.text_field %> :</h6>
       <p  class="mx-3" ><%= comment.created_at %> </p>
    <br>
    <br>
    <% end %> 
<% end %>
</div>
</div>
</div>
   
</section>




<% if user_signed_in? %>
  <% if @item.user_id == current_user.id %>
    <%= link_to "Edit", edit_items_path(@item)%>
     <%= link_to 'Delete', @item, method: :delete, data: { confirm: 'Are you sure?' } %>
     <%end%>
<%end%>





 
<br>
<br>
<br>